### ISSUE TITLE
No Longer Possible to Move the Firefox Window (not even with the suggested workarounds now)

### ISSUE THREAD

**Issue by xeonx1** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#312]
Dragging the titlebar no longer results in the Firefox window being moved, regardless of workarounds discussed in #296 and elsewhere.
And, the workaround now required for issue #311 means that there is absolutely no way whatsoever to move the Firefox window (not even by dragging a space in the toolbar or tabbar background, which otherwise used to work).

This seems like it might be a new issue possibly due to the extension no longer being compatible with the latest version of Firefox.
This issue occurs with both Hide Caption Titlebar Plus Dev Channel (3.0.6rc) and Stable (v3.0.5) versions with Firefox Developer Edition 64-bit build (47.0a2 (2016-03-15)) with Windows 10 x64.

The issue occurs with both standard and private windows, even though I am using Personas (LightweightTheme) and even when I tried to use the style suggested in #296 comments - those workarounds had no effect (regardless of the System Titlebar option).

Neither setting Enable Controls/Widgets to Drag-Window = All nor enabled Drag FX Window Using Tab-bar background = Yes or any other of the many settings I had tried resolved this issue.
Though those settings allowed me to drag the window using a space I added to the toolbar, even that fails to work when I have "System Titlebar (almost) always present" option enabled (in order to workaround issue #311 

@Javier-DarthPalpatine

**Comment by vovcacik** [comment]
I can confirm this issue. I have got exactly the same platform as @xeonx1 mentioned in first post.

**Comment by vovcacik** [comment]
This issue is tricky. I believe there was Firefox version that allowed to drag the window by space in toolbar without persona installed, but can't find it now. Anyway the current release version 45.0.1 lets you drag window by space in toolbar if you got persona installed. Current aurora 47.0a2 won't, even if you install persona.

@xeonx1 is this the main aspect of your issue report? Or should I file new one, after all you refer to *Dragging the titlebar* and I am not sure if it is the same thing as my *space in toolbar* (which is the space between buttons or the few pixels above url input field etc.).

**Comment by xeonx1** [comment]
WORKAROUND: 
Set "Enable Customizable Buttons (min,max,close)" to "No (Fx. default)" (under Hide Caption Titlebar Plus Options > Look & Feel) in order to restore support for dragging the Firefox titlebar to move the Firefox window.
In other words, "extensions.hide_caption.plus.adv.sysbut_winappear" under about:config should have a value of "" (empty string).

Setting this to "No" fixes drag titlebar (caption) to move for *both* the 1) custom caption titlebar (eg. "System Titlebar always hidden" enabled and "Show Custom Caption/TitleBar" = "In unmaximized windows OR "Small Caption" (instead of "Never")) and 2) the system caption titlebar ("Firefox option: System TitleBar (almost) always present" enabled), regardless of whether "browser.tabs.drawInTitlebar" is true or false (something I found others reporting used to be related to drag to move not working).

In case relevant, I do have a persona in use and haven't tested without it.


SUGGESTED FIX:
I suggest not just making "No" the default setting, but marking it as Recommended (currently Glass and Solid are recommended) with a warning for that option or alternative values for it.

If it can't be quickly fixed so that all values for this preference still allow dragging the titlebar to move the window then I would also suggest automatically resetting this to No for everyone - possibly either by either:
A) ignoring any value for extensions.hide_caption.plus.adv.sysbut_winappear which doesn't have "override" or "force" in the string value (since the value is a list of keywords depended on what's selected under Options), or 
B) renaming the preference so that  "extensions.hide_caption.plus.adv.sysbut_winappear" is ignored or deleted and only a new renamed setting like extensions.hide_caption.plus.adv.sysbut_winappear_disabledragtitlebartomove" is used instead.

Note:
Please note that the "drag titlebar to move not working" issue otherwise occurs (when Enable Customizable Buttons is not "No") even when all other settings effective disable custom caption buttons (eg. Enable Customizable = Solid, Custom Window Background (which is relates to whether Persona is active) = No, Custom Minimize Max, and Close Buttons In (Un)Maximized Window = Enabled, Skin = New..) and regardless of any other combination of those settings.
to that string order to ignore any previously selected or default preference value to automatically fix this issue for everyone.]=

**Comment by xeonx1** [comment]
@vovcacik 
I think I have pinpointed the cause of the "drag window using space in toolbar" issue you had reported, along with a workaround, as well as few related issues I haven't yet seen reported:
(Note: have just tested so far with Persona enabled)

WORKAROUND for Drag Toolbar Space to Move Window not working:

1. Add a space element to the toolbar by: App button > Customize, then drag a "Space" element (3 stacked box icon) or "Flexible Space" to the toolbar. 
(This is needed because just dragging the background behind the toolbar icons doesn't work)

2. Either
A) Set "Enable Customizable Buttons (min, max, close)" = "No", OR
B) Uncheck "Firefox option: System TitleBar (almost) always present" (which results in browser.tabs.drawInTitlebar = true). 
  NOTE:: You may need to temporarily uncheck "System TitleBar always hidden" in order to change that option, otherwise its grayed out (and still needs to be unchecked even if its grayed out)

3. In theory, you should also have to set "Enable Controls/Widgets to Drag-Window" (under Advanced Settings  > Drag-Window) to "All" (or at least "All except other addons Space Widgets (default)" ), however, for me, this setting is always ignored, leading me to report the following new related issue, reported below:

**Comment by xeonx1** [comment]
## Related Issue:  Can't Remove Spaces when Customizing Toolbar
Space and Flexible Space elementss can only be removed from toolbars inn Customize mode when "Firefox option: System TitleBar (almost) always present" is checked (when browser.tabs.drawInTitlebar = false).

### SUGGESTED FIX:

Therefore, you could probably fix this just by disabling the "drag space widget" behavior when in Customize mode. 
This seems to be the case because apparently the System titlebar isn't actually required to be shown in order for this to work, because enabling "Firefox option: System TitleBar (almost) always present" **fixes this issue even when system titlebar isn't actually shown, due to "System titlebar always hidden" also being enabled.**

**Comment by xeonx1** [comment]
## 3 Issues when drawInTitlebar = true

Disabling "Firefox option: System TitleBar (almost) always present" (under Look & Feel > System TitleBar - or leaving it unchecked as the Hide Caption default / recommended setting - so that browser.tabs.drawInTitlebar = true - results in numerous issues occurring, including the following (and possibly more):

1) You can't remove Space and Flexible Space elements when Customizing Toolbars 

2) Left tabbar scrollbar doesn't respond to clicks (if one is shown eg. when have many tabs with tabbar positioned on the left with Tree Style Tabs) and instead results in maximizing/restoring window if double clicking on it. (See Issue #311 )

3) Double clicking near any edge of a non-maximized window results in maximizing the window (even when inside the window, so that no resize cursor is shown) (eg. bottom or left scrollbar, or even far right side of toolbar or sometimes anywhere on far right if no scrollbar, sidebar, or sidebar switch is shown there) results (See Issue #311 )

However, you can see by enabling "System TitleBar always hidden" - after also enabling "Firefox option: System TitleBar (almost) always present" that these issues go away - even though the custom titlebar is being shown instead of the system title.
Because of this, I suggest


SUGGESTED FIX:

1) Replace "System titlebar always hidden" checkbox with a "TitleBar Type Shown" drop-down (shown above "Show Custom Caption / TitleBar" instead of at the bottom) with values "Always Force Custom" | "Custom when fully supported (Recommended)" | "Always System" by replacing "extensions.hide_caption.plus.sys.forbid_fxaustr_syscaption" (and display related uses of  "browser.tabs.drawInTitlebar = false") with extensions.hide_caption.plus.sys.syscaption = true | false | "" (default - empty string).

2A) Modify any input (eg. click/drag) logic to treat as if always have "browser.tabs.drawInTitlebar = false" and modify any display logic to only use the new extensions.hide_caption.plus.sys.syscaption (drop-down, OR:

2B) Have browser.tabs.drawInTitlebar set to false on first install (or upgrade to) the new version (which is currently equivalent to by checking "Firefox option: System TitleBar (almost) always present") and rename it to "Show Tabs in TitleBar (recommended: unchecked, to allow drag to move window)".

**Comment by vovcacik** [comment]
@xeonx1 thanks for workaround 2.A) it works, however it only creates small draggable space underneath the min/max/close buttons, but it also enables draggability to spacer widgets so thats great. Other space in toolbar that used to be draggable is still affected by the bug (e.g. the few pixels above URL input field used to be draggable).

2.B) does not work for me. Step 3) seems to have no effect for me.

**Comment by Javier-DarthPalpatine** [comment]
Hi!

I've hopefully FIXED  1) all DRAGGING & Un/Maximizing-by-dblClick issues and  2) the Spaces customizing issues, in a PRERELEASE version that I've uploaded here:

   [http://tiny.cc/darth_moz](http://tiny.cc/darth_moz)     goto 'HCTP' > 'New'  (file:  hidecaptionplus-308pre)

   [direct link:](https://drive.google.com/open?id=0B0CsJE3K6Lk-TFhNMllYRXkwMFE#list)

Could you please try it and let me know how it goes? 

Thanks a lot to both of you! for all your detailed reports and suggestions!
J

PS: 
* I've merged/moved other similar issues with this. Please let me know if there is any further issue in such reports that maybe I didn't realize yet.

* All dragging/dblClicking and customizing issues appeared bc of some mayor changes in Fx47+, AFAICT.
* I've also fixed some layout issues with non-default themes, including hctp's custom borders that *may* help to the issue mentioned with Tree-Style-Tabs's scrollbar.

**Comment by Winterwolf** [comment]
Still can't un/maximize with dbl-click (Linux Mint 17.3 Cinnamon).

**Comment by Javier-DarthPalpatine** [comment]
TESTED ver 308pre in Windows 7 64, Fx 46b, 47a & 48a.

**Comment by vovcacik** [comment]
### Testing 308pre Win 8:

- [x] all DRAGGING issues **SOMEWHAT FIXED**
  - [x] dragging by titlebar (the default HCTP titlebar) regardless personas **FIXED**
  - [ ] dragging by space in toolbar with a persona installed **NOT FIXED**
- [x] all Un/Maximizing-by-dblClick issues **FIXED**
- [x] the Spaces customizing issues **FIXED**

Still can't drag the window by free space in toolbar. If the Firefox did some substantial change to UI I think getting that feature back would be **significant pain**. It does impact my UX, but I don't think it's worth your time.

I consider the issue to be resolved. Thanks for fixing it!

**Comment by Javier-DarthPalpatine** [comment]
>> Testing 308pre Win 8:
>> dragging by space in toolbar with a persona installed **NOT FIXED**

That's in latest Fx 47a? 
I'll try again, It shouldn't be a prob to solve it.
Tks!

**Comment by vovcacik** [comment]
@Javier-DarthPalpatine yes, comment updated. Thanks for giving it a second look!

**Comment by irvinm** [comment]
I tried 3.0.9rc and dragging windows works for me again.  Thanks.

Question:  The "[h] Drag Window" item works fine as a drag point when the window is not maximized, but when the window is maximized it disappears.  Is that by design?  

I think the previous behavior was that it was always present and if the window was maximized, you would grab it, the window would "restore" to its pre-maximized state, and you could drag the window at that point.  (You can obviously achieve the same thing still by first "restoring" the window via the minimize-restore-close buttons then dragging ... just an extra step now)

**Comment by xeonx1** [comment]
@Javier-DarthPalpatine 
3.0.9rc breaks all previous workarounds for vertical tabs (not page content) scrollbar (for Tree Style Tabs positioned on the left, etc.), so that now attempting to scroll down to more/overflow tabs always results in moving the window or maximizing the window instead.

See my [latest comment](https://github.com/Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus/issues/311#issuecomment-226369932) for issue #311 for details.
